### PR TITLE
 Keep Deployment paused on Rollout deletion

### LINKED ISSUE #272: keep pause=true when rollout CR is deleted
currently, when rollout CR is deleted, rollout controller will recover the deployment to its original spec, which also including the spec.paused field. However this may result  in deployment rolling release, which is unexpected for many users. 

It is desirable to have the ability to keep the deployment as is when rollout is deleted, that is

- still recover the deployment strategy to its original setting but leave the pause remain to be true.
- add a featuregate to switch the behavior when rollout is deleted.

### PR DESCRIPTION
**Pull request by GautamBytes**
### Ⅰ. Describe what this PR does
This PR addresses an issue where deleting a Rollout CR causes the controller to unpause the underlying Deployment, triggering an unexpected rolling update.

To solve this, a new feature has been added to keep the Deployment paused when its managing Rollout is deleted. This behavior is controlled by a new feature gate, KeepDeploymentPausedOnDeletionGate. When the gate is enabled, the rollout finalizer will skip the step that unpauses the Deployment, leaving it in its static, paused state. This change has been applied to both Canary and Blue-Green strategies for consistent behavior.

### Ⅱ. Does this pull request fix one issue?

Fixes #272 

### Ⅲ. Special notes for reviews
- The key aspect of this change is the introduction of the KeepDeploymentPausedOnDeletionGate feature gate.

- The new behavior is disabled by default to ensure full backward compatibility.
Users must explicitly enable the feature gate to prevent the Deployment from being unpaused upon Rollout deletion. This makes the feature entirely opt-in.

### CODE REVIEW

**Comment by GautamBytes** [comment]
@furykerry , Can you help me in identifying why Unit-Test CL workflow is failing even though i ran 'make generate manifests' and pushed the auto-generated files as mentioned in workflow file

File: pkg/controller/rollout/rollout_bluegreen.go [hunk 1]
```diff
@@ -305,7 +309,27 @@ func (m *blueGreenReleaseManager) doCanaryFinalising(c *RolloutContext) (bool, e
 	switch blueGreenStatus.FinalisingStep {
 	// set workload.pause=false; set workload.partition=0
 	case v1beta1.FinalisingStepResumeWorkload:
-		retry, err = finalizingBatchRelease(m.Client, c)
+		// If the rollout is being deleted and the feature gate is enabled,
+		// we skip this step entirely to keep the deployment paused.
+		if c.FinalizeReason == v1beta1.FinaliseReasonDelete && utilfeature.DefaultMutableFeatureGate.Enabled(feature.KeepDeploymentPausedOnDeletionGate) {
+			klog.Infof("Rollout(%s/%s) is being deleted, KeepDeploymentPausedOnDeletion is enabled. Skipping resume workload step.", c.Rollout.Namespace, c.Rollout.Name)
+			// Do nothing, effectively skipping this step and considering it "done".
+		} else {
```
Comment (furykerry) [inline pkg/controller/rollout/rollout_bluegreen.go:317]: we cannot simply change deployment here, instead, we should change the Finalize method for the following packages:
1. pkg/controller/batchrelease/control/partitionstyle
2. pkg/controller/batchrelease/control/canarystyle
3. pkg/controller/batchrelease/control/bluegreenstyle

**Comment by AiRanthem** [comment]
I believe the behavior of Rollout when handling deletion/disable should be as follows:

1. The Rollout controller patches the `batchPartition` field of the corresponding `BatchRelease` object to null
2. The BatchRelease controller executes the Finalize method for the corresponding release type (which is the part you modified)
3. Execute the Finalize method of the corresponding workload to restore it to its original state
4. After successfully restoring the workload, the BatchRelease enters the `Completed` state
5. The Rollout controller deletes the BatchRelease resource

Therefore, this PR may have the following issues:

1. It completely skips the workload restoration. The logic should be moved down, only keeping the deployment's `pause=true`, and the logic of removing annotations, labels, and **changing the strategy back to RollingUpdate**, which is important, still needs to be executed
2. Have you considered implementing the protection logic for other workloads together:

| workload    | partition                 | canary      | blue-green               |
|-------------|---------------------------|-------------|--------------------------|
| Deployment  | retain `pause=true`         | skip deleting canary | retain `pause=true` and `maxSurge` |
| StatefulSet | retain `partition`          | /           | /                        |
| CloneSet    | retain `pause=true` and `partition` |             | retain `pause=true` and `maxSurge` |
| DaemonSet   | retain `pause=true` and `partition` | /           | /                        |

@furykerry @zmberg What do you think of the modification plan in the table?

**Comment by furykerry** [comment]
we can discuss it in the next community call. For canary and blue-green deployment, if we keep the workload as it is, it is quite hard for the user to recover the workload and traffic.

**Comment by furykerry** [comment]
@GautamBytes KeepDeploymentPausedOnDeletionGate only make sense for partitionStyle strategy currently, consider remove the changes for canary and bluegreen strategy
